name: RUN BOT

on:
  workflow_dispatch
  
jobs:
  process-lectures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lecture processing script
        run: |
          python main.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

